server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userAuthenticationDb?createDatabaseIfNotExist=true
    username: root
    password: TejasPatil143
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-authentication-service
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: kanbanboard.niit@gmail.com
    password: wlxjuknbkrxoabec
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true
