version: '3.3'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: mongo
    network_mode: host

mysql:
  image: mysql:5.5
  ports:
    - 3306:3306
  container_name: mysqlservice
  network_mode: host
  hostname: localhost
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USERNAME: user
    MYSQL_PASSWORD: root
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

eurekaServer:
  image: eureka-server
  build: EurekaServer/
  restart: "no"
  network_mode: host
  environment:
    EUREKA_SERVER_PORT: 8761
  ports:
    - 8761:8761

cloudapiservice:
  image: cloud-api-service
  build: ApiGateway/
  restart: "no"
  network_mode: host
  ports:
    - 9000:9000
  environment:
    API_GATEWAY_PORT: 9000
    EUREKA_SERVER_IP: localhost
    EUREKA_SERVER_PORT: 8761
  depends_on:
    - eurekaServer

userauthservice:
  container_name: user-auth-service
  build: UserAuthenticationService/
  restart: "no"
  network_mode: host
  hostname: localhost
  depends_on:
    - mysql
    - eurekaServer
    - cloudapiservice
  ports:
    - 8081:8081

kanbanservice:
  container_name: kanban-service
  build: kanbanservice/
  restart: "no"
  hostname: localhost
  network_mode: host
  depends_on:
    - mongo
    - eurekaServer
    - cloudapiservice
  ports:
    - 8082:8082